//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raiting
    {
        public int id { get; set; }
        public int accountID { get; set; }
        public int postID { get; set; }
        public int mark { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Mark Mark1 { get; set; }
        public virtual Post Post { get; set; }
    }
}
